live_config_reload = true
import = [ "~/.config/alacritty/themes/themes/monokai_charcoal.yml" ]

[window]
dynamic_title = true
opacity = 0.7

[cursor]
style = {shape = "Beam"}
vi_mode_style = {shape ="Underline"}

[selection]
save_to_clipboard = true

[scrolling]
history = 2_000

[shell]
program = "/usr/bin/zsh"

[font]
normal = {family = "Hack Nerd Font Mono", style = "Regular"}
bold = {family = "Hack Nerd Font Mono", style = "Bold"}
italic = {family = "Hack Nerd Font Mono", style = "Regualr Italic"}
font.bold_italic = {family = "Hack Nerd Font Mono", style = "Bold Italic"}

[keyboard]
key = "Space"
mods = "Shift|Control"
mode = "~Vi|Search"
action = "ToggleViMode"

