theme = "onedarker"

[editor]
line-number = "relative"
auto-completion = true 
color-modes = true
auto-pairs = true
mouse = true
auto-format = true
auto-info = true

[editor.file-picker]
hidden = false

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-signature-help-docs = true
snippets = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
j = { j = "normal_mode" }

[keys.normal]
g = { a = "code_action" }

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "register"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
