-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ! Auto-generated file. Do not edit directly.

-- Remove source = ./dms/colors.conf from your config to override.

local primary = "rgb(dcb8ff)"

local outline = "rgb(988d9e)"

local error = "rgb(ffb4ab)"

hl.config({
    general = {
        col = {
            active_border = "rgb(dcb8ff)",
            inactive_border = "rgb(988d9e)",
        },
    },
})

hl.config({
    group = {
        groupbar = {
            col.active = "rgb(dcb8ff)",
            col.inactive = "rgb(988d9e)",
            col.locked_active = "rgb(ffb4ab)",
            col.locked_inactive = "rgb(988d9e)",
        },
        col = {
            border_active = "rgb(dcb8ff)",
            border_inactive = "rgb(988d9e)",
            border_locked_active = "rgb(ffb4ab)",
            border_locked_inactive = "rgb(988d9e)",
        },
    },
})
