-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

--

-- name "Vertical"

-- credit https://github.com/prasanthrangan/hyprdots

hl.config({
    animations = {
        enabled = true,
        -- Windows
        -- window open
        -- window close.
        -- everything in between, moving, dragging, resizing.
        -- Fading
        -- Layers
        -- Workspaces
        --animation = workspaces, 1, 3, fluent_decel, slidefade 30% # styles: slide, slidevert, fade, slidefade, slidefadevert
        -- styles: slide, slidevert, fade, slidefade, slidefadevert
    },
})
