-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

--

-- name "Default"

-- credit https://github.com/prasanthrangan/hyprdots

hl.config({
    animations = {
        enabled = true,
    },
})
