-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- Hyprlock config for => 2k monitor resolutions                                                         

-- Original config submitted by https://github.com/SherLock707

-- Sourcing colors generated by wallust

-- source = $HOME/.config/hypr/wallust/wallust-hyprland.conf -> requires manual conversion
-- local wallust-hyprland = require("wallust-hyprland")
-- TODO: convert $HOME/.config/hypr/wallust/wallust-hyprland.conf to .lua and use require()

local Scripts = "local_var_HOME/.config/hypr/scripts"

hl.config({
    general = {
        grace = 1,
        fractional_scaling = 2,
        immediate_render = true,
    },
})

hl.config({
    background = {
        -- NOTE: use only 1 path
        --path = screenshot   # screenshot of your desktop
        --path = $HOME/.config/hypr/wallpaper_effects/.wallpaper_modified # by wallpaper effects
        path = HOME/.config/hypr/wallpaper_effects/.wallpaper_current,
        -- current wallpaper
        color = { "rgb(0", 0, "0)" },
        -- color will be rendered initially until path is available
        -- all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
        blur_size = 3,
        blur_passes = 2,
        -- 0 disables blurring
        noise = 0.0117,
        contrast = 1.3000,
        -- Vibrant!!!
        brightness = 0.8000,
        vibrancy = 0.2100,
        vibrancy_darkness = 0.0,
    },
})
-- NOTE: Section 'background' may be a plugin or custom section; verify the output

-- Date

hl.config({
    label = {
        text = { "cmd[update:18000000] echo <b>  $(date +'%A", "%-d %B')  </b>" },
        color = color13,
        font_size = 18,
        font_family = "Victor Mono Bold Italic",
        position = { 0, -120 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- Hour-Time

hl.config({
    label = {
        text = "cmd[update:1000] echo $(date + %H )",
        --    text = cmd[update:1000] echo "$(date +"%I")" #AM/PM
        --color = rgba(255, 185, 0, .8)
        color = color13,
        font_size = 240,
        font_family = "JetBrainsMono Nerd Font ExtraBold",
        position = { 0, -100 },
        halign = "center",
        valign = "top",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- Minute-Time

hl.config({
    label = {
        text = "cmd[update:1000] echo $(date + %M )",
        --color = rgba(15, 10, 222, .8)
        color = color12,
        font_size = 240,
        font_family = "JetBrainsMono Nerd Font ExtraBold",
        position = { 0, -450 },
        halign = "center",
        valign = "top",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- Seconds-Time

hl.config({
    label = {
        text = "cmd[update:1000] echo $(date + %S )",
        --    text = cmd[update:1000] echo "$(date +"%S %p")" #AM/PM
        color = color11,
        font_size = 50,
        font_family = "JetBrainsMono Nerd Font ExtraBold",
        position = { 0, -450 },
        halign = "center",
        valign = "top",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- Put a picture of choice here. Default is the current wallpaper

--image {

--    monitor =

--    #path = $HOME/.config/hypr/wallpaper_effects/.wallpaper_current

--    size = 160

--    rounding = -1

--    border_size = 0

--    border_color = $color11

--    rotate = 0

--    reload_time = -1

--    position = 0, 400

--    halign = center

--    valign = bottom

--}

-- USER

hl.config({
    label = {
        text = " local_var_USER",
        color = color13,
        font_size = 24,
        font_family = "Victor Mono Bold Oblique",
        position = { 0, 200 },
        halign = "center",
        valign = "bottom",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- INPUT FIELD

hl.config({
    input-field = {
        size = { 300, 60 },
        outline_thickness = 2,
        dots_size = 0.2,
        -- Scale of input-field height, 0.2 - 0.8
        dots_spacing = 0.2,
        -- Scale of dots' absolute size, 0.0 - 1.0
        dots_center = true,
        outer_color = color11,
        inner_color = { "rgba(255", 255, 255, "0.1)" },
        font_color = color13,
        capslock_color = { "rgb(255", 255, "255)" },
        fade_on_empty = false,
        font_family = "Victor Mono Bold Oblique",
        placeholder_text = "<i><span foreground=##ffffff99 >🔒 Type Password</span></i>",
        hide_input = false,
        position = { 0, 100 },
        halign = "center",
        valign = "bottom",
    },
})
-- NOTE: Section 'input-field' may be a plugin or custom section; verify the output

-- uptime

hl.config({
    label = {
        text = "cmd[update:60000] echo <b>  $(uptime -p || local_var_HOME/.config/hypr/scripts/UptimeNixOS.sh)  </b>",
        color = color13,
        font_size = 18,
        font_family = "Victor Mono Bold Oblique",
        position = { 0, 0 },
        halign = "right",
        valign = "bottom",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- weather edit the scripts for locations

-- weather scripts are located in ~/.config/hypr/UserScripts Weather.sh and/or Weather.py

-- see https://github.com/JaKooLit/Hyprland-Dots/wiki/TIPS#%EF%B8%8F-weather-app-related-for-waybar-and-hyprlock

hl.config({
    label = {
        text = "cmd[update:3600000] [ -f local_var_HOME/.cache/.weather_cache ] && cat local_var_HOME/.cache/.weather_cache",
        color = color13,
        font_size = 18,
        font_family = "Victor Mono Bold Oblique",
        position = { 50, 0 },
        halign = "left",
        valign = "bottom",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output
