-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- TODO: manual review: preload = "/usr/share/hyprland/wall_2K.png"

-- TODO: manual review: preload = "/usr/share/hyprland/wall_anime_2K.png"

-- TODO: manual review: preload = "/usr/share/hyprland/wall_anime2_2K.png"

-- TODO: manual review: wallpaper = "VGA-1", "/usr/share/hyprland/wall_anime_2K.png"
