-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more variable settings

-- These configs are mostly for laptops. This is addemdum to Keybinds.conf

local mainMod = "SUPER"

local scriptsDir = "local_var_HOME/.config/hypr/scripts"

local UserConfigs = "local_var_HOME/.config/hypr/UserConfigs"

-- for disabling Touchpad. hyprctl devices to get device name. 

local Touchpad_Device = "asue1209:00-04f3:319f-touchpad"

hl.bind("xf86KbdBrightnessDown", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/BrightnessKbd.sh --dec"))

-- decrease keyboard brightness

hl.bind("xf86KbdBrightnessUp", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/BrightnessKbd.sh --inc"))

-- increase keyboard brightness

hl.bind("xf86Launch1", hl.dsp.exec_cmd("rog-control-center"))

-- ASUS Armory crate button

hl.bind("xf86Launch3", hl.dsp.exec_cmd("asusctl led-mode -n"))

-- FN+F4 Switch keyboard RGB profile 

hl.bind("xf86Launch4", hl.dsp.exec_cmd("asusctl profile -n"))

-- FN+F5 change of fan profiles (Quite, Balance, Performance)

hl.bind("xf86MonBrightnessDown", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/Brightness.sh --dec"))

-- decrease monitor brightness

hl.bind("xf86MonBrightnessUp", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/Brightness.sh --inc"))

-- increase monitor brightness

hl.bind("xf86TouchpadToggle", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/TouchPad.sh"))

-- disable touchpad

-- Screenshot keybindings using F6 (no PrinSrc button)

hl.bind(mainMod .. " + " .. "F6", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/ScreenShot.sh --now"))

-- screenshot

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F6", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/ScreenShot.sh --area"))

-- screenshot (area)

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "F6", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/ScreenShot.sh --in5"))

-- # screenshot (5 secs delay)

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "F6", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/ScreenShot.sh --in10"))

-- screenshot (10 secs delay)

hl.bind("ALT" .. " + " .. "F6", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/ScreenShot.sh --active"))

-- screenshot (active window only)

local TOUCHPAD_ENABLED = true

hl.device({
    name = "$Touchpad_Device",
    enabled = true,
})

-- Below are useful when you are connecting your laptop in external display

-- Suggest you edit below for your laptop display

-- From WIKI This is to disable laptop monitor when lid is closed.

-- consult https://wiki.hyprland.org/hyprland-wiki/pages/Configuring/Binds/#switches

--bindl = , switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, preferred, auto, 1"

--bindl = , switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"

-- WARNING! Using this method has some caveats!! USE THIS PART WITH SOME CAUTION!

-- CONS of doing this, is that you need to set up your wallpaper (SUPER W) and choose wallpaper.

-- CAVEATS! Sometimes the Main Laptop Monitor DOES NOT have display that it needs to re-connect your external monitor

-- One work around is to ensure that before shutting down laptop, MAKE SURE your laptop lid is OPEN!!

-- Make sure to comment (put # on the both the bindl = , switch ......) above

-- NOTE: Display for laptop are being generated into LaptopDisplay.conf

-- This part is to be use if you do not want your main laptop monitor to wake up during say wallpaper change etc

--bindl = , switch:off:Lid Switch,exec,echo "monitor = eDP-1, preferred, auto, 1" > $UserConfigs/LaptopDisplay.conf

--bindl = , switch:on:Lid Switch,exec,echo "monitor = eDP-1, disable" > $UserConfigs/LaptopDisplay.conf

-- for laptop-lid action (to erase the last entry)

--exec-once = echo "monitor = eDP-1, preferred, auto, 1" > $HOME/.config/hypr/UserConfigs/LaptopDisplay.conf

--
