-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

--

-- name "Me-2"

-- credit https://github.com/mahaveergurjar

hl.config({
    animations = {
        enabled = true,
        --used by rainbow borders and rotating colors
        -- animations for -git or version >0.42.0
    },
})
