-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

--

-- name "Me-1"

-- credit https://github.com/mahaveergurjar

hl.config({
    animations = {
        enabled = true,
        -- Animation curves
        -- bezier = linear, 0, 0, 1, 1
        -- use with .2s duration
        -- Animation configs
        -- animation = windows, 1, 3, md3_decel, popin 60%
        -- animation = windowsIn, 1, 3, md3_decel, popin 60%
        -- animation = windowsOut, 1, 3, md3_accel, popin 60%
        -- animation = windows, 1, 6, wind, slide
        -- animation = border, 1, 10, default
        -- animation = layers, 1, 2, md3_decel, slide
        -- animation = workspaces, 1, 2.5, softAcDecel, slide
        -- animation = workspaces, 1, 7, menu_decel, slidefade 15%
    },
})
