-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- Commands and Apps to be executed at launch

local scriptsDir = "local_var_HOME/.config/hypr/scripts"

local UserScripts = "local_var_HOME/.config/hypr/UserScripts"

local wallDIR = "local_var_HOME/Pictures/wallpapers"

local lock = "local_var_HOME/.config/hypr/scripts/LockScreen.sh"

local SwwwRandom = "local_var_HOME/.config/hypr/UserScripts/WallpaperAutoChange.sh"

local livewallpaper = ""

-- wallpaper stuff 


--exec-once = mpvpaper '*' -o "load-scripts=no no-audio --loop" $livewallpaper

-- wallpaper random


-- random wallpaper switcher every 30 minutes

-- Startup



-- Polkit (Polkit Gnome / KDE)


-- starup apps





--exec-once = rog-control-center


--clipboard manager



-- Rainbow borders


-- Starting hypridle to start hyprlock


-- Here are list of features available but disabled by default

-- exec-once = swww-daemon --format xrgb && swww img $HOME/Pictures/wallpapers/mecha-nostalgia.png  # persistent wallpaper

--gnome polkit for nixos

--exec-once = $scriptsDir/Polkit-NixOS.sh

-- xdg-desktop-portal-hyprland (should be auto starting. However, you can force to start)

--exec-once = $scriptsDir/PortalHyprland.sh

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("swww-daemon --format xrgb")
    hl.exec_cmd("local_var_HOME/.config/hypr/UserScripts/WallpaperAutoChange.sh local_var_HOME/Pictures/wallpapers")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("local_var_HOME/.config/hypr/scripts/Polkit.sh")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("swaync")
    hl.exec_cmd("ags")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("waybar")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("local_var_HOME/.config/hypr/UserScripts/RainbowBorders.sh")
    hl.exec_cmd("hypridle")
end)
