-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- Decoration Settings

-- Hyprland Wiki Links

-- Animation - https://wiki.hyprland.org/Configuring/Animations/

-- Decoration - https://wiki.hyprland.org/Configuring/Variables/#decoration

-- Sourcing colors generated by wallust

-- source = $HOME/.config/hypr/wallust/wallust-hyprland.conf -> requires manual conversion
-- local wallust-hyprland = require("wallust-hyprland")
-- TODO: convert $HOME/.config/hypr/wallust/wallust-hyprland.conf to .lua and use require()

hl.config({
    general = {
        border_size = 2,
        gaps_in = 2,
        gaps_out = 4,
        col = {
            active_border = color12,
            inactive_border = color10,
        },
    },
})

hl.config({
    decoration = {
        rounding = 10,
        active_opacity = 1.0,
        inactive_opacity = 0.9,
        fullscreen_opacity = 1.0,
        dim_inactive = true,
        dim_strength = 0.1,
        dim_special = 0.8,
        shadow = {
            enabled = true,
            range = 3,
            render_power = 1,
            color = color12,
            color_inactive = color10,
        },
        blur = {
            enabled = true,
            size = 6,
            passes = 2,
            ignore_opacity = true,
            new_optimizations = true,
            special = true,
            popups = true,
        },
    },
})

hl.config({
    group = {
        groupbar = {
            col.active = color0,
        },
        col = {
            border_active = color15,
        },
    },
})
