-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- This is where you put your own keybinds. Be Mindful to check as well ~/.config/hypr/configs/Keybinds.conf to avoid conflict

-- if you think I should replace the Pre-defined Keybinds in ~/.config/hypr/configs/Keybinds.conf , submit an issue or let me know in DC and present me a valid reason as to why, such as conflicting with global shortcuts, etc etc

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more settings and variables

-- See also Laptops.conf for laptops keybinds 

-- /* ---- ✴️ Variables ✴️ ---- */  #

local mainMod = "SUPER"

local files = "thunar"

local term = "kitty"

local scriptsDir = "local_var_HOME/.config/hypr/scripts"

local UserScripts = "local_var_HOME/.config/hypr/UserScripts"

-- common shortcuts

--bindr = $mainMod, $mainMod_L, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window # Super Key to Launch rofi menu

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("pkill rofi || true && rofi -show drun -modi drun,filebrowser,run,window"))

-- Main Menu (APP Launcher)

hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd("xdg-open https://"))

-- default browser

hl.bind(mainMod .. " + " .. "A", hl.dsp.exec_cmd("pkill rofi || true && ags -t 'overview'"))

-- desktop overview (if installed)

hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd("kitty"))

--terminal

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("thunar"))

--file manager

hl.bind(mainMod .. " + " .. "F1", hl.dsp.exec_cmd("thorium-browser"))

hl.bind(mainMod .. " + " .. "F2", hl.dsp.exec_cmd("warp-terminal"))

hl.bind(mainMod .. " + " .. "F3", hl.dsp.exec_cmd("ghostty"))

-- Back and Forth

hl.bind(mainMod .. " + " .. "TAB", hl.dsp.focus({ workspace = "previous" }))

-- FEATURES / EXTRAS

hl.bind(mainMod .. " + " .. "H", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/KeyHints.sh"))

-- help / cheat sheet

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "R", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/Refresh.sh"))

-- Refresh waybar, swaync, rofi

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "E", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/RofiEmoji.sh"))

-- emoji menu

hl.bind(mainMod .. " + " .. "S", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/RofiSearch.sh"))

-- Google search using rofi

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "O", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/ChangeBlur.sh"))

-- Toggle blur settings 

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "G", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/GameMode.sh"))

-- Toggle animations ON/OFF

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "L", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/ChangeLayout.sh"))

-- Toggle Master or Dwindle Layout

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "V", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/ClipManager.sh"))

-- Clipboard Manager

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "R", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/RofiThemeSelector.sh"))

-- KooL Rofi Menu Theme Selector

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("pkill rofi || true && local_var_HOME/.config/hypr/scripts/RofiThemeSelector-modified.sh"))

-- modified Rofi Theme Selector

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.fullscreen())

-- whole full screen

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "F", hl.dsp.window.fullscreen())

-- fake full screen

hl.bind(mainMod .. " + " .. "SPACE", hl.dsp.window.float())

--Float Mode

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "SPACE", hl.dsp.exec_cmd("hyprctl dispatch workspaceopt allfloat"))

--All Float Mode

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Return", hl.dsp.exec_cmd("[float; move 15% 5%; size 70% 60%] kitty"))

-- Dropdown terminal

-- Desktop zooming or magnifier

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "mouse_down", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = local_var_2; if (factor < 1) {factor = 1}; print factor * 2.0}')"))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "mouse_up", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = local_var_2; if (factor < 1) {factor = 1}; print factor / 2.0}')"))

--# NOTES for ja (Hyprland version 0.39 (Ubuntu 24.04))

--bind = $mainMod ALT, mouse_down, exec, hyprctl keyword misc:cursor_zoom_factor "$(hyprctl getoption misc:cursor_zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor * 2.0}')"

--bind = $mainMod ALT, mouse_up, exec, hyprctl keyword misc:cursor_zoom_factor "$(hyprctl getoption misc:cursor_zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor / 2.0}')" 

-- Waybar / Bar related

hl.bind(mainMod .. " + " .. "CTRL + ALT" .. " + " .. "B", hl.dsp.exec_cmd("pkill -SIGUSR1 waybar"))

-- Toggle hide/show waybar 

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "B", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/WaybarStyles.sh"))

-- Waybar Styles Menu

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "B", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/WaybarLayout.sh"))

-- Waybar Layout Menu

-- FEATURES / EXTRAS (UserScripts)

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "M", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/UserScripts/RofiBeats.sh"))

-- online music using rofi

hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/UserScripts/WallpaperSelect.sh"))

-- Select wallpaper to apply

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/UserScripts/WallpaperEffects.sh"))

-- Wallpaper Effects by imagemagick

hl.bind("CTRL + ALT" .. " + " .. "W", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/UserScripts/WallpaperRandom.sh"))

-- Random wallpapers

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "O", hl.dsp.exec_cmd("hyprctl setprop active opaque toggle"))

-- disable opacity on active window

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "K", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/KeyBinds.sh"))

-- search keybinds via rofi

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "A", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/Animations.sh"))

--hyprland animations menu

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "O", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/UserScripts/ZshChangeTheme.sh"))

-- Change oh-my-zsh theme

hl.bind("ALT_L" .. " + " .. "SHIFT_L", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/SwitchKeyboardLayout.sh"), { locked = true, non_consuming = true })

-- Change keyboard layout

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "C", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/UserScripts/RofiCalc.sh"))

-- calculator (qalculate)

-- For passthrough keyboard into a VM

-- bind = $mainMod ALT, P, submap, passthru

--submap = passthru

-- to unbind

--bind = $mainMod ALT, P, submap, reset

--submap = reset
