hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY")
    hl.exec_cmd("systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user enable --now hypridle")
    hl.exec_cmd("/usr/bin/mate-polkit")
    hl.exec_cmd("xdg-user-dirs-update")
    hl.exec_cmd("pikman-update-manager-autostart")
    hl.exec_cmd("dconf write /org/gnome/desktop/interface/cursor-size 24")
    hl.exec_cmd("gsettings set org.cinnamon.desktop.default-applications.terminal exec kitty")
    hl.exec_cmd("swww-daemon")
    hl.exec_cmd("pikabar")
    hl.exec_cmd("test -e /live/filesystem.squashfs && pika-installer")
    hl.exec_cmd("test -e /live/filesystem.squashfs && test -e /home/pikaos && pika-first-setup-gtk4")
    hl.exec_cmd("test -e /home/pikaos && pika-welcome-autostart")
end)
