-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- as per Hyprland wiki: hyprland-qt-support provides a QML style for hypr* qt6 apps                                                         

-- TODO: manual review: roundess = 2

-- TODO: manual review: border_width = 0

-- TODO: manual review: reduce_motion = false
