-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- always refer to Hyprland wiki

-- https://wiki.hyprland.org/

-- Initial boot script enable to apply initial wallpapers, theming, new settings etc.

-- suggest not to change this or delete this including deleting referrence file in ~/.config/hypr/.initial_startup_done

-- as long as the referrence file is present, this initial-boot.sh will not execute


-- Sourcing external config files

local configs = "local_var_HOME/.config/hypr/configs"

-- Default Configs directory path

-- source = $configs/Keybinds.conf -> requires manual conversion
-- local Keybinds = require("Keybinds")
-- TODO: convert $configs/Keybinds.conf to .lua and use require()

-- Pre-configured keybinds

-- ## This is where you want to start tinkering 

local UserConfigs = "local_var_HOME/.config/hypr/UserConfigs"

-- User Configs directory path

-- source = $UserConfigs/Startup_Apps.conf -> requires manual conversion
-- local Startup_Apps = require("Startup_Apps")
-- TODO: convert $UserConfigs/Startup_Apps.conf to .lua and use require()

-- put your start-up packages on this file

-- source = $UserConfigs/ENVariables.conf -> requires manual conversion
-- local ENVariables = require("ENVariables")
-- TODO: convert $UserConfigs/ENVariables.conf to .lua and use require()

-- Environment variables to load

--source= $UserConfigs/Monitors.conf # Its all about your monitor config (old dots) will remove on push to main

--source= $UserConfigs/WorkspaceRules.conf # Hyprland workspaces (old dots) will remove on push to main

-- source = $UserConfigs/Laptops.conf -> requires manual conversion
-- local Laptops = require("Laptops")
-- TODO: convert $UserConfigs/Laptops.conf to .lua and use require()

-- For laptop related

-- source = $UserConfigs/LaptopDisplay.conf -> requires manual conversion
-- local LaptopDisplay = require("LaptopDisplay")
-- TODO: convert $UserConfigs/LaptopDisplay.conf to .lua and use require()

-- Laptop display related. You need to read the comment on this file

-- source = $UserConfigs/WindowRules.conf -> requires manual conversion
-- local WindowRules = require("WindowRules")
-- TODO: convert $UserConfigs/WindowRules.conf to .lua and use require()

-- all about Hyprland Window Rules and Layer Rules

-- source = $UserConfigs/UserDecorations.conf -> requires manual conversion
-- local UserDecorations = require("UserDecorations")
-- TODO: convert $UserConfigs/UserDecorations.conf to .lua and use require()

-- Decorations config file

-- source = $UserConfigs/UserAnimations.conf -> requires manual conversion
-- local UserAnimations = require("UserAnimations")
-- TODO: convert $UserConfigs/UserAnimations.conf to .lua and use require()

-- Animation config file

-- source = $UserConfigs/UserKeybinds.conf -> requires manual conversion
-- local UserKeybinds = require("UserKeybinds")
-- TODO: convert $UserConfigs/UserKeybinds.conf to .lua and use require()

-- Put your own keybinds here

-- source = $UserConfigs/UserSettings.conf -> requires manual conversion
-- local UserSettings = require("UserSettings")
-- TODO: convert $UserConfigs/UserSettings.conf to .lua and use require()

-- Main Hyprland Settings.

-- source = $UserConfigs/01-UserDefaults.conf -> requires manual conversion
-- local 01-UserDefaults = require("01-UserDefaults")
-- TODO: convert $UserConfigs/01-UserDefaults.conf to .lua and use require()

-- settings for User defaults apps

-- nwg-displays

-- source = $HOME/.config/hypr/monitors.conf -> requires manual conversion
-- local monitors = require("monitors")
-- TODO: convert $HOME/.config/hypr/monitors.conf to .lua and use require()

-- source = $HOME/.config/hypr/workspaces.conf -> requires manual conversion
-- local workspaces = require("workspaces")
-- TODO: convert $HOME/.config/hypr/workspaces.conf to .lua and use require()

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("local_var_HOME/.config/hypr/initial-boot.sh")
end)
