-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
-- Always refer to Hyprland wiki
-- https://wiki.hyprland.org/

-- Initial boot script enable to apply initial wallpapers, theming, new settings etc.
-- suggest not to change this or delete this including deleting referrence file in ~/.config/hypr/.initial_startup_done
-- as long as the referrence file is present, this initial-boot.sh will not execute
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

--## Sourcing external config files ###
local configs = HOME .. "/.config/hypr/configs" -- Default Configs directory path
local UserConfigs = HOME .. "/.config/hypr/UserConfigs" -- User Configs directory path

-- Source: $configs/Keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_configs.Keybinds")

-- Load defaults, then user additions/overrides
-- Source: $configs/Startup_Apps.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_configs.Startup_Apps")
-- Source: $UserConfigs/Startup_Apps.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs.Startup_Apps")

-- Source: $configs/ENVariables.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_configs.ENVariables")
-- Source: $UserConfigs/ENVariables.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs.ENVariables")

-- For laptop related
-- Source: $configs/Laptops.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_configs.Laptops")
-- Source: $UserConfigs/Laptops.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs.Laptops")
-- Source: $UserConfigs/LaptopDisplay.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs.LaptopDisplay")

-- Load defaults, then user additions
-- Source: $configs/WindowRules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_configs.WindowRules")
-- Source: $UserConfigs/WindowRules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs.WindowRules")

-- Source: $configs/SystemSettings.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_configs.SystemSettings")

-- Source: $UserConfigs/UserDecorations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs.UserDecorations")
-- Source: $UserConfigs/UserAnimations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs.UserAnimations")
-- Source: $UserConfigs/UserKeybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs.UserKeybinds")
-- Source: $UserConfigs/UserSettings.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs.UserSettings")
-- Source: $UserConfigs/01-UserDefaults.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_UserConfigs._01-UserDefaults")

-- nwg-displays
-- Source: $HOME/.config/hypr/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_HOME._config.hypr.monitors")
-- Source: $HOME/.config/hypr/workspaces.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_HOME._config.hypr.workspaces")

hl.on("hyprland.start", function()
    hl.exec_cmd("$HOME/.config/hypr/initial-boot.sh")
end)

