-- Generated by nwg-displays on 2026-06-19 at 03:20:04. Do not edit manually.

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@60.0",
    position = "1920x0",
    scale = "1.0",
})

hl.monitor({
    output = "DP-2",
    mode = "1920x1080@75.0",
    position = "3840x120",
    scale = "1.0",
})

