- name: Install packages on Arch Linux
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: Install package using pacman
      community.general.pacman:
        name:
          - alacritty
          - alsa-firmware
          - alsa-plugins
          - alsa-utils
          - android-tools
          - ansible
          - ansible-core
          - arandr
          - arch-install-scripts
          - archlinux-tweak-tool-git
          - arcolinux-arc-aqua-git
          - arcolinux-arc-blueberry-git
          - arcolinux-arc-botticelli-git
          - arcolinux-arc-darkish-git
          - arcolinux-arc-dawn-git
          - arcolinux-arc-dodger-blue-git
          - arcolinux-arc-dracul-git
          - arcolinux-arc-emerald-git
          - arcolinux-arc-fire-git
          - arcolinux-arc-kde
          - arcolinux-arc-light-blue-surfn-git
          - arcolinux-arc-numix-git
          - arcolinux-arc-pale-grey-git
          - arcolinux-arc-punch-git
          - arcolinux-arc-purpley-git
          - arcolinux-arc-slate-grey-git
          - arcolinux-arc-smoke-git
          - arcolinux-arc-tacao-git
          - arcolinux-arc-vampire-git
          - ark
          - atuin
          - base
          - base-devel
          - bash-completion
          - bat
          - bc
          - binder_linux-dkms
          - biome
          - bleachbit
          - bluedevil
          - bluefish
          - blueman
          - bluez-tools
          - bmon
          - boxbuddy
          - brave-bin
          - breeze
          - breeze-gtk
          - breeze-plymouth
          - brightnessctl
          - btop
          - catfish
          - cava
          - chaotic-keyring
          - chaotic-mirrorlist
          - clang
          - cliphist
          - clipmenu
          - copyq
          - cosmic-app-library
          - cosmic-applets
          - cosmic-bg
          - cosmic-comp
          - cosmic-files
          - cosmic-greeter
          - cosmic-idle
          - cosmic-launcher
          - cosmic-notifications
          - cosmic-osd
          - cosmic-panel
          - cosmic-randr
          - cosmic-screenshot
          - cosmic-session
          - cosmic-settings
          - cosmic-settings-daemon
          - cosmic-store
          - cosmic-terminal
          - cosmic-text-editor
          - cosmic-wallpapers
          - cosmic-workspaces
          - cowsay
          - cryfs
          - dbeaver
          - dconf-editor
          - dhclient
          - direnv
          - discover
          - distrobox
          - dkms
          - dmenu
          - dmidecode
          - dnsmasq
          - docker
          - dolphin-plugins
          - dosfstools
          - drkonqi
          - edu-vimix-dark-tela-git
          - encfs
          - evince
          - exfat-utils
          - exo
          - eza
          - fastfetch
          - fd
          - feh
          - ffmpegthumbnailer
          - ffmpegthumbs
          - firefox
          - fish
          - flameshot
          - flatpak
          - flatpak-kcm
          - fzf
          - garcon
          - git
          - git-credential-manager-bin
          - github-cli
          - gnome-calculator
          - gnome-text-editor
          - gnu-netcat
          - go
          - gocryptfs
          - grim
          - grimblast-git
          - grub
          - gst-plugins-bad
          - gst-plugins-ugly
          - gtk4
          - gvfs
          - gwenview
          - htop
          - hyprland
          - hyprpicker
          - hyprshade
          - i3lock-color
          - imagemagick
          - imv
          - incus
          - incus-tools
          - incus-ui
          - intel-ucode
          - inxi
          - iptables-nft
          - jetbrains-toolbox
          - jq
          - kactivitymanagerd
          - kate
          - kde-cli-tools
          - kde-gtk-config
          - kde-system-meta
          - kdeconnect
          - kdenetwork-filesharing
          - kdeplasma-addons
          - kgamma
          - kglobalacceld
          - kinfocenter
          - kmenuedit
          - kpipewire
          - krdp
          - kscreen
          - kscreenlocker
          - ksshaskpass
          - ksystemstats
          - ktorrent
          - kvantum
          - kwallet-pam
          - kwayland
          - kwin
          - kwrited
          - lastpass
          - layer-shell-qt
          - lazygit
          - less
          - libadwaita
          - libayatana-appindicator
          - libconfig
          - libev
          - libkscreen
          - libksysguard
          - libplasma
          - libvirt
          - lightdm-gtk-greeter-settings
          - linux-cachyos
          - linux-cachyos-headers
          - linux-firmware
          - linux-lts
          - linux-lts-headers
          - linux-zen
          - linux-zen-headers
          - lolcat
          - loupe
          - lxappearance
          - mandoc
          - mate-polkit
          - meld
          - meson
          - milou
          - mpv
          - mypy
          - nautilus
          - nautilus-open-any-terminal
          - neo-candy-icons-git
          - neovim
          - netstat-nat
          - network-manager-applet
          - networkmanager
          - nitrogen
          - nm-connection-editor
          - nmap
          - nodejs-lts-jod
          - noto-fonts-cjk
          - noto-fonts-emoji
          - noto-fonts-extra
          - npm
          - ntfs-3g
          - ntp
          - nwg-dock-hyprland
          - nwg-look
          - ocean-sound-theme
          - ocs-url
          - oh-my-posh-bin
          - okular
          - os-prober
          - otf-font-awesome
          - oxygen
          - oxygen-sounds
          - packagekit-qt6
          - pacman-contrib
          - pacseek
          - papirus-icon-theme
          - pavucontrol
          - picom
          - pinta
          - pipewire-alsa
          - plasma-activities
          - plasma-activities-stats
          - plasma-browser-integration
          - plasma-desktop
          - plasma-disks
          - plasma-firewall
          - plasma-integration
          - plasma-nm
          - plasma-pa
          - plasma-sdk
          - plasma-systemmonitor
          - plasma-thunderbolt
          - plasma-vault
          - plasma-welcome
          - plasma-workspace
          - plasma-workspace-wallpapers
          - plasma5support
          - plymouth-kcm
          - podman
          - podman-compose
          - polkit-gnome
          - polkit-kde-agent
          - polybar
          - power-profiles-daemon
          - powerdevil
          - print-manager
          - pulseaudio-alsa
          - pwvucontrol
          - pyenv
          - python-black
          - python-dateutil
          - python-iwlib
          - python-netifaces2
          - python-pip
          - python-pipx
          - python-pyclip
          - python-screeninfo
          - qemu-desktop
          - qemu-emulators-full
          - qqc2-breeze-style
          - qt6ct
          - qtile
          - qtile-extras-git
          - quickemu-git
          - ranger
          - redshift
          - reflector
          - ripgrep
          - rofi
          - rsync
          - rustup
          - sardi-orb-colora-variations-icons-git
          - scrcpy
          - scrot
          - sddm
          - sddm-kcm
          - slurp
          - sparklines-git
          - spectacle
          - sqlite-doc
          - sshpass
          - starship
          - stow
          - sublime-text-4
          - surfn-plasma-dark-icons-git
          - surfn-plasma-flow-git
          - surfraw
          - swaync
          - swtpm
          - swww
          - sxhkd
          - systemsettings
          - tailscale
          - terminus-font
          - thunar
          - thunar-volman
          - tk
          - tldr
          - tmux
          - toilet
          - traceroute
          - ttf-dejavu
          - ttf-fira-code
          - ttf-fira-sans
          - ttf-firacode-nerd
          - tumbler
          - ueberzug
          - ufw
          - unifetch
          - unzip
          - uthash
          - uwsm
          - valgrind
          - variety
          - virt-manager
          - virtualbox
          - virtualbox-ext-oracle
          - virtualbox-ext-vnc
          - virtualbox-guest-iso
          - virtualbox-guest-utils
          - virtualbox-host-dkms
          - visual-studio-code-bin
          - wacomtablet
          - waybar
          - waydroid
          - waydroid-image-gapps
          - wget
          - wlogout
          - wofi
          - wttr
          - xclip
          - xcolor
          - xdg-desktop-portal-cosmic
          - xdg-desktop-portal-gtk
          - xdg-desktop-portal-kde
          - xf86-video-amdgpu
          - xfce4-appfinder
          - xfce4-cpufreq-plugin
          - xfce4-cpugraph-plugin
          - xfce4-diskperf-plugin
          - xfce4-docklike-plugin
          - xfce4-hotcorner-plugin-git
          - xfce4-netload-plugin
          - xfce4-panel
          - xfce4-power-manager
          - xfce4-pulseaudio-plugin
          - xfce4-session
          - xfce4-settings
          - xfce4-terminal
          - xfdesktop
          - xfwm4
          - xfwm4-themes
          - xorg-server
          - xorg-xinit
          - xorg-xkill
          - xorg-xrandr
          - yakuake
          - yq
          - zed
          - zig
          - zls
          - zoxide
          - zsh
          - zsh-completions
          - zsh-syntax-highlighting